// Web Worker for extracting YouTube videos using yt-dlp & Innertube engine
import type { VideoInfo, VideoFormat, SubtitleTrack } from '../types';

function formatBytes(bytes?: number): string {
  if (!bytes || bytes === 0) return 'Dinamik Akış';
  const k = 1024;
  const sizes = ['Bytes', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
}

function formatDuration(seconds?: number): string {
  if (!seconds) return '0:00';
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  const hrs = Math.floor(mins / 60);
  const remainingMins = mins % 60;
  
  if (hrs > 0) {
    return `${hrs}:${remainingMins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  }
  return `${mins}:${secs.toString().padStart(2, '0')}`;
}

function formatViewCount(views?: number): string {
  if (!views) return '0 görüntülenme';
  if (views >= 1_000_000_000) return (views / 1_000_000_000).toFixed(1) + ' Mr görüntülenme';
  if (views >= 1_000_000) return (views / 1_000_000).toFixed(1) + ' Mn görüntülenme';
  if (views >= 1_000) return (views / 1_000).toFixed(1) + ' B görüntülenme';
  return views.toLocaleString() + ' görüntülenme';
}

function parseYtDlpOutput(data: any, originalUrl: string): VideoInfo {
  const formats: VideoFormat[] = [];
  const audioFormats: VideoFormat[] = [];

  const rawFormats = data.formats || [];

  // Filter and sort audio streams
  const audioStreams = rawFormats.filter((f: any) => 
    f.url && (f.vcodec === 'none' || !f.vcodec) && (f.acodec && f.acodec !== 'none')
  );
  audioStreams.sort((a: any, b: any) => (b.tbr || b.abr || 0) - (a.tbr || a.abr || 0));
  const bestAudioStream = audioStreams[0];

  for (const f of rawFormats) {
    if (!f.url) continue;

    const isVideo = f.vcodec && f.vcodec !== 'none';
    const isAudio = f.acodec && f.acodec !== 'none';
    const isAdaptive = isVideo && !isAudio;

    const qualityLabel = f.format_note || (f.height ? `${f.height}p` : `${Math.round(f.tbr || 128)} kbps`);
    const size = f.filesize || f.filesize_approx;

    const formatObj: VideoFormat = {
      formatId: String(f.format_id),
      qualityLabel: qualityLabel,
      resolution: f.resolution || (f.width && f.height ? `${f.width}x${f.height}` : undefined),
      fps: f.fps,
      ext: f.ext || (isAudio ? 'm4a' : 'mp4'),
      filesize: size,
      filesizeFormatted: formatBytes(size),
      videoCodec: f.vcodec,
      audioCodec: f.acodec,
      hasVideo: isVideo,
      hasAudio: isAudio,
      isAdaptive: isAdaptive,
      url: f.url,
      audioUrl: isAdaptive && bestAudioStream ? bestAudioStream.url : undefined,
      audioFormatId: isAdaptive && bestAudioStream ? String(bestAudioStream.format_id) : undefined,
      bitrate: f.tbr,
    };

    if (isVideo) {
      formats.push(formatObj);
    } else if (isAudio) {
      audioFormats.push(formatObj);
    }
  }

  // Sort video formats by height/resolution descending
  formats.sort((a, b) => {
    const resA = parseInt(a.qualityLabel) || 0;
    const resB = parseInt(b.qualityLabel) || 0;
    return resB - resA;
  });

  const subtitles: SubtitleTrack[] = [];
  if (data.subtitles) {
    for (const [lang, trackList] of Object.entries(data.subtitles) as [string, any[]][]) {
      const bestTrack = trackList?.[0];
      if (bestTrack) {
        subtitles.push({
          languageCode: lang,
          languageName: bestTrack.name || lang,
          url: bestTrack.url,
          ext: bestTrack.ext || 'vtt',
          isAutoGenerated: false,
        });
      }
    }
  }

  return {
    id: data.id || 'video',
    title: data.title || 'YouTube Video',
    channel: data.uploader || data.channel || 'YouTube Kanalı',
    channelUrl: data.uploader_url || data.channel_url,
    duration: data.duration || 0,
    durationFormatted: formatDuration(data.duration),
    viewCount: data.view_count || 0,
    viewCountFormatted: formatViewCount(data.view_count),
    uploadDate: data.upload_date ? `${data.upload_date.slice(6,8)}.${data.upload_date.slice(4,6)}.${data.upload_date.slice(0,4)}` : new Date().toLocaleDateString('tr-TR'),
    thumbnailUrl: data.thumbnail || `https://i.ytimg.com/vi/${data.id}/hqdefault.jpg`,
    description: data.description || '',
    formats,
    audioFormats,
    subtitles,
    originalUrl,
  };
}

function parseInnertubeOutput(data: any, videoId: string, originalUrl: string): VideoInfo {
  const videoDetails = data.videoDetails || {};
  const streamingData = data.streamingData || {};

  const formats: VideoFormat[] = [];
  const audioFormats: VideoFormat[] = [];

  const rawFormats = [
    ...(streamingData.formats || []),
    ...(streamingData.adaptiveFormats || [])
  ];

  const audioStreams = rawFormats.filter((f: any) => f.mimeType?.startsWith('audio/'));
  audioStreams.sort((a: any, b: any) => (b.bitrate || 0) - (a.bitrate || 0));
  const bestAudioStream = audioStreams[0];

  for (const f of rawFormats) {
    if (!f.url) continue;

    const isVideo = f.mimeType?.startsWith('video/');
    const isAudio = f.mimeType?.startsWith('audio/');
    const isAdaptive = isVideo && !f.audioQuality;

    const formatObj: VideoFormat = {
      formatId: String(f.itag),
      qualityLabel: f.qualityLabel || (isAudio ? `${Math.round((f.bitrate || 128000) / 1000)} kbps` : `${f.height || 360}p`),
      resolution: f.width && f.height ? `${f.width}x${f.height}` : undefined,
      fps: f.fps,
      ext: f.mimeType?.includes('webm') ? 'webm' : (isAudio ? 'm4a' : 'mp4'),
      filesize: f.contentLength ? parseInt(f.contentLength, 10) : undefined,
      filesizeFormatted: formatBytes(f.contentLength ? parseInt(f.contentLength, 10) : undefined),
      videoCodec: f.mimeType?.split('codecs="')?.[1]?.split('"')?.[0],
      hasVideo: isVideo,
      hasAudio: isAudio || Boolean(f.audioQuality),
      isAdaptive: isAdaptive,
      url: f.url,
      audioUrl: isAdaptive && bestAudioStream ? bestAudioStream.url : undefined,
      audioFormatId: isAdaptive && bestAudioStream ? String(bestAudioStream.itag) : undefined,
      bitrate: f.bitrate,
    };

    if (isVideo) {
      formats.push(formatObj);
    } else if (isAudio) {
      audioFormats.push(formatObj);
    }
  }

  formats.sort((a, b) => {
    const resA = parseInt(a.qualityLabel) || 0;
    const resB = parseInt(b.qualityLabel) || 0;
    return resB - resA;
  });

  const durationSec = parseInt(videoDetails.lengthSeconds || '0', 10);

  return {
    id: videoId,
    title: videoDetails.title || 'YouTube Video',
    channel: videoDetails.author || 'YouTube Kanalı',
    channelUrl: `https://www.youtube.com/channel/${videoDetails.channelId}`,
    duration: durationSec,
    durationFormatted: formatDuration(durationSec),
    viewCount: parseInt(videoDetails.viewCount || '0', 10),
    viewCountFormatted: formatViewCount(parseInt(videoDetails.viewCount || '0', 10)),
    uploadDate: new Date().toLocaleDateString('tr-TR'),
    thumbnailUrl: videoDetails.thumbnail?.thumbnails?.slice(-1)[0]?.url || `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
    description: videoDetails.shortDescription || '',
    formats,
    audioFormats,
    subtitles: [],
    originalUrl,
  };
}

async function extractVideo(url: string, proxyUrl: string): Promise<VideoInfo> {
  const match = url.match(/(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?.+&v=|shorts\/))([\w-]{11})/);
  if (!match) {
    throw new Error('Geçersiz YouTube bağlantısı. Lütfen geçerli bir video veya Shorts URL girin.');
  }
  const videoId = match[1];


  // 2. Fallback: Secondary External Endpoint
  const apiKey = 'AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8';
  const directApiUrl = `https://www.youtube.com/youtubei/v1/player?key=${apiKey}&prettyPrint=false`;
  const targetEndpoint = proxyUrl 
    ? `${proxyUrl}${encodeURIComponent(directApiUrl)}`
    : `https://corsproxy.io/?url=${encodeURIComponent(directApiUrl)}`;

  const res = await fetch(targetEndpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-YouTube-Client-Name': '55',
      'X-YouTube-Client-Version': '1.56.21',
    },
    body: JSON.stringify({
      context: {
        client: {
          clientName: 'ANDROID_VR',
          clientVersion: '1.56.21',
          deviceMake: 'Oculus',
          deviceModel: 'Quest 3',
          osName: 'Android',
          osVersion: '12',
          hl: 'tr',
          gl: 'TR',
        },
      },
      videoId,
      contentCheckOk: true,
      racyCheckOk: true,
    }),
  });

  if (!res.ok) {
    throw new Error(`YouTube video bilgileri alınamadı (${res.status}).`);
  }

  const data = await res.json();
  if (data.playabilityStatus?.status !== 'OK') {
    throw new Error(data.playabilityStatus?.reason || 'Bu video oynatılamıyor veya gizli/kısıtlı.');
  }

  return parseInnertubeOutput(data, videoId, url);
}

// Listen to main thread messages
self.onmessage = async (e: MessageEvent) => {
  const { action, payload, id } = e.data;

  if (action === 'extract') {
    const { url, proxyUrl } = payload;
    self.postMessage({ type: 'status', message: 'yt-dlp ile doğrudan video akışları ve formatlar taranıyor...' });

    try {
      const videoInfo = await extractVideo(url, proxyUrl);
      self.postMessage({ id, type: 'extract_success', data: videoInfo });
    } catch (err: any) {
      self.postMessage({ 
        id, 
        type: 'extract_error', 
        error: err?.message || 'Video bilgileri çekilemedi.' 
      });
    }
  }
};
