export interface VideoFormat {
  formatId: string;
  qualityLabel: string;
  resolution?: string;
  fps?: number;
  ext: 'mp4' | 'webm' | 'm4a' | 'mp3' | 'opus' | string;
  filesize?: number;
  filesizeFormatted?: string;
  videoCodec?: string;
  audioCodec?: string;
  hasVideo: boolean;
  hasAudio: boolean;
  isAdaptive: boolean; // True if separate video and audio streams need to be muxed
  url: string;
  audioUrl?: string; // Companion audio URL for muxing
  audioFormatId?: string;
  bitrate?: number;
}

export interface SubtitleTrack {
  languageCode: string;
  languageName: string;
  url: string;
  ext: 'vtt' | 'srt';
  isAutoGenerated: boolean;
}

export interface VideoInfo {
  id: string;
  title: string;
  channel: string;
  channelUrl?: string;
  channelAvatar?: string;
  duration: number; // in seconds
  durationFormatted: string;
  viewCount: number;
  viewCountFormatted: string;
  uploadDate: string;
  thumbnailUrl: string;
  description: string;
  formats: VideoFormat[];
  audioFormats: VideoFormat[];
  subtitles: SubtitleTrack[];
  originalUrl: string;
}

export type DownloadStage = 
  | 'idle'
  | 'initializing'
  | 'extracting'
  | 'downloading_video'
  | 'downloading_audio'
  | 'muxing'
  | 'converting_audio'
  | 'saving'
  | 'completed'
  | 'error';

export interface DownloadProgress {
  stage: DownloadStage;
  percentage: number; // 0 to 100
  downloadedBytes: number;
  totalBytes: number;
  speed: number; // bytes per second
  speedFormatted: string;
  etaSeconds: number;
  statusMessage: string;
  error?: string;
}

export interface AppSettings {
  corsProxyUrl: string;
  customProxyList: string[];
  theme: 'dark' | 'light';
  useFileSystemAccess: boolean;
  audioBitrate: '320k' | '256k' | '192k' | '128k';
  defaultFormat: 'video_best' | 'audio_mp3';
  debugLogs: boolean;
}

export interface WorkerLogMessage {
  type: 'log' | 'error' | 'status' | 'ready';
  message: string;
  data?: any;
}
